tray:
    icon:
        file: "tray-icon.png"
        tooltip: "Amplifier control"
mqtt:
    serverUrl: "tcp://192.168.1.128:1883"
    clientId: amplifier_control
    autoReconnect: true
    username: <mqtt_username>
    password: <mqtt_password>
amplifier:
    mqtt:
        topic: "/amplifier/command"
        payload:
            volume_up: "VOLUME_UP"
            volume_down: "VOLUME_DOWN"
            mute: "MUTE"
            source: "SOURCE"
climate:
    mqtt:
        topic: "/climate/command"
        payload:
            temp_up: "TEMP_UP"
            temp_down: "TEMP_DOWN"
